driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: pester

platforms:
  - name: windows-10
    driver_config:
      box: chef/windows-10-enterprise
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: windows-2016-chef-12.6
    driver_config:
      box: chef/windows-server-2016-standard
    provisioner:
      require_chef_omnibus: 12.7.2

suites:
  - name: basic
    run_list:
      - recipe[test::basic]
