Layout/EndOfLine:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'resources/status.rb'

Style/GlobalVars:
  Exclude:
    - 'libraries/defender_helper.rb'

Lint/UselessAssignment:
  Exclude:
    - 'resources/status.rb'
    - 'resources/config.rb'
