Layout/EndOfLine:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'resources/status.rb'

Style/Next:
  Exclude:
    - 'resources/configure.rb'

Lint/UselessAssignment:
  Exclude:
    - 'resources/status.rb'
    - 'resources/config.rb'
